export const PermitSelectionSummaryKeys = [
  {
    ref: 'dart-extn-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-mod-ren-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to modify/renew/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to ',
    modifyContainerTitleSuffix:'/renew/transfer the following permit(s):'
  },
  {
    ref: 'dart-extn-mod-renew',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/modify/renew the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to extend/',
    modifyContainerTitleSuffix:'/renew the following permit(s):'
  },
  {
    ref: 'dart-mod-ren',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to modify/renew the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to ',
    modifyContainerTitleSuffix:'/renew the following permit(s):',
    
  },
  {
    ref: 'dart-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-mod',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to modify the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to  ',
    modifyContainerTitleSuffix:' the following permit(s):'
  },
  {
    ref: 'dart-ren-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to renew/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-extn-mod',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/modify the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to extend/',
    modifyContainerTitleSuffix:' the following permit(s):'
  },
  {
    ref: 'dart-extn-renew-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/renew/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-pending-txr',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:'',
  },
  {
    ref: 'dart-extn',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-extn-renew',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/renew the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  {
    ref: 'dart-extn-mod-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/modify/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to extend/',
    modifyContainerTitleSuffix:'/transfer the following permit(s):'
  },
  {
    ref: 'dart-extn-mod-renew-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to extend/modify/renew/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to extend/',
    modifyContainerTitleSuffix:'/renew/transfer the following permit(s):',
  },
  {
    ref: 'dart-mod-transfer',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to modify/transfer the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:true,
    modifyContainerTitlePrefix:'You are applying to ',
    modifyContainerTitleSuffix:'/transfer the following permit(s): '
  },
  {
    ref: 'dart-ren',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying to renew the following permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
  
  {
    ref: 'etrack-permits',
    containerRole: '',
    containerAriaLabel: '',
    containerAriaDescribedBy: '',
    containerTitle: 'You are applying for the following new permit(s):',
    tableAriaLabel: '',
    tableAriaDescribedBy: '',
    modify:false,
    modifyContainerTitlePrefix:'',
    modifyContainerTitleSuffix:''
  },
];
