export class SIProject {
  searchBy!: string;
  street!: string;
  city!: string;
  state: string='NY';
  zip!: string;
  searchByMunicipality!:string;
  searchByCounty!:string;
  searchByTaxParcel!:string;
  inquiryId!:number;
  polygonId!:number;
  reason!: string;
  region!: string;
  borough!:string;
  block!: string;
  lot!: string;
  requestorName!: string;
  streetAddress!: string;
  mailingAddress!: string;
  mailingAddressStreet1!: string;
  mailingAddressStreet2!: string;
  mailingAddressZip!: string;
  mailingAddressState!: string;
  mailingAddressCity!: string;
  phoneNumber!: string;
  projectName!: string;
  projectDescription!: string;
  projectSponsor!: string;
  issuesQuestions!: string;
  leadAgencyName!: string;
  leadAgencyContact!: string;
  efcContact!: string;
  planName!:string;
  planDescription!: string;
  extenderName!: string;
  dowContact!: string;
  developer!: string;
  owner!: string;
  pscDocketNum!: string;
  comments!: string;
  email!: string;
  taxParcel!: string;
  county!: string;
  municipality!: string;
  //receivedDate!:Date;
  response!:string;
  responseDate!:Date;
}
