package dec.ny.gov.etrack.dart.db.model;

public enum CurrentDartStatus {

  PRE_APPLICATION("1"),
  COMPLETENESS_DETERMINATION_DUE("2"),
  WRITTEN_COMMENTS_DEADLINE("3"),
  HEARING_DECISION_DUE("4"),
  FINAL_DECISION_DUE("5"),
  PERMITTEE_RESPONSE_DUE("6"),
  DIMSR_DECISION_DUE("7"),
  INCOMPLETE("9"),
  ISSUED("10"),
  WITHDRAWN_BY_APPLICANT("11"),
  NO_JURISDICTION("12"),
  DENIED("13"),
  DISCONTINUED("14"),
  INSUFFICIENT_INFORMATION("15"),
  CONTINUE_PERMIT("16"),
  MODIFY_PERMIT("17"),
  SUSPEND_PERMIT("18"),
  REVOKE_PERMIT("19"),
  SUSPENDED_TO_A_DATE("20"),
  SUSPENDED_INDEFINITELY("21"),
  NEW_APPLICATION_NEEDED("22"),
  EXTENDED_INDEFINITELY("23"),
  WQC_WAIVER("24"),
  CONCEPTUAL_REVIEW("25"),
  CONSENT_ORDER("26"),
  UNKNOWN("27"),
  EXPIRED("28"),
  REVIEW_REFUSED("29"),
  SAPA_EXTENDED("30"),
  PRE_PERMIT("31"),
  INCOMPLETE_FOR_1_YEAR("32"),
  CHRONICALLY_INCOMPLETE("33"),
  WITHDRAWN_FOR_INCOMPLETENESS("34"),
  PENDING("35"),
  IN_REVIEW("36"),
  APPROVED("37"),
  APPLICANT_RESPONSE_DUE("38"),
  INSUFFICIENT("39"),
  BLANKET_APPROVAL("40");
  
  private String value;
  
  CurrentDartStatus(String value) {
    this.value = value;
  }
  
  public String getCurrrentStatus() {
    return this.value;
  }
}
